### PR TITLE
With css and shuffle

### PR DESCRIPTION
**Pull request by Samcfuchs**
Basically, the most important changes are updated css to make it look nice and some javascript to implement shuffle.

### CODE REVIEW

**Comment by Sgeo** [comment]
A few concerns:
- Some of the commit messages don't really match the commit, like "Added title" does a whole bunch of other things
- The shuffle feature is hardcoded to use a random number between 1 and 19. This should be changed to be more flexible when new songs are added (and/or songs are removed which I hope doesn't happen but could). Also adding a class to the song buttons and selecting among those is probably better than needing to start from 1 and skip the Shuffle button in that way
- `audioplayer.loop` is set to false only during initialization, but the handler for the buttons sets it to true on click, so the second shuffled song will repeat forever. Could fix this by moving `audioplayer.loop = false` to `function shuffle()`, after `button.click()`
- I don't really like that it's not obvious that the mp3 and ogg links are clickable.
- Maybe a way to make it clear that shuffle "mode" is on-off, and a way to leave shuffling, for that matter.
- console.log might break in IE9 and below, although admittedly I haven't even tested normal functionality in IE9 anyway.

Thank you for contributing!

**Comment by Sgeo** [comment]
Correction, you'll also need to reset `audioplayer.onended = shuffle` inside `shuffle()` as well. The net effect is that clicking a non-shuffle button turns off "shuffle mode" (in quotes because it's not an actually-tracked mode, just seems like it), clicking shuffle activates it. I'm not totally sure if that's ideal, but it seems to work.

**Comment by Samcfuchs** [comment]
Ok, tackling one at a time.

Yeah, sometimes I waited too long to commit or I lumped in other changes, so I just titled the commiti with the most obvious/important change.

I'm not familiar with json, so I'm not sure how to get the length of that string hosted on koalabeast. Is it easy enough for you to tell me here?

Easy enough to copy that code into shuffle().

The links - that's just css, pretty straightforward. I changed it for stylistic purposes, but I can fix that.

I mean, you leave shuffle mode by clicking on a song, and demonstrating that it's a toggle would be pretty hard. I see what you mean, but that's a lot more work and I think the user would figure it out.

I'll remove console.log, that's just for debug anyways.

I'll comment here as I fix these.

**Comment by Samcfuchs** [comment]
Shuffle problem is fixed

**Comment by Samcfuchs** [comment]
Downloads now look clickable

**Comment by Samcfuchs** [comment]
Console.log is removed

**Comment by Sgeo** [comment]
- Some people have told me that git rebase -i is capable of renaming commits, although to be honest, I'm not sure how to use that. But I really would like to see those commits renamed to be more reflective of the changes.
- The JSON object is available in init() as data (an array), and the length is accessible via data.length, as seen in the for loop. Two approaches I can see: Create a shuffle function within init that uses data.length, and attach to the shuffle button with addEventListener. Or it could just count the number of song buttons (easier if there's a special class for song buttons). I think that the first option is the cleaner approach, but the second might be easier, since it "cheats" by using the DOM, which your code does anyway, so it's probably not a big deal.

**Comment by Samcfuchs** [comment]
I've fixed some of the commit titles. Are there any that still need work?

**Comment by Samcfuchs** [comment]
I actually didn't have to cheat using DOM. I just made a global variable to hold the data and accessed that from shuffle(). Anything else?

**Comment by Sgeo** [comment]
I actually really don't like global variables, but I'll merge, as long as it works I can clean it up later.

**Comment by Samcfuchs** [comment]
Thanks!

**Pull request merged**
